--- 
# (TODO) Change this to user to run AST as.
user: example
# (TODO) Change this to where AST is installed.
cwd: /home/example/ast/current
log_file: log/mongrel.log
port: "4500"
environment: production
group: ops
address: 127.0.0.1
pid_file: tmp/pids/mongrel.pid
servers: 8
